version: "3.5"
services:
    mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: pwd
            MYSQL_USER: user
            MYSQL_PASSWORD: pwd
            MYSQL_DATABASE: dev
        volumes:
            - ./src/db:/docker-entrypoint-initdb.d/
            - db_data:/var/lib/mysql
volumes:
    db_data: